import argparse
import csv
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Sequence
from xml.sax.saxutils import escape


EXPORT_COLUMNS = [
    "IceID",
    "MappedID",
    "Hotel",
    "AssetType",
    "Index",
    "PublicID",
    "Category",
    "Custom Tags",
    "Caption",
    "Description",
    "Alt Text",
    "URL",
]

SOURCE_COLUMNS = {
    "IceID": "Listing_ICEID",
    "MappedID": "Listing_MappedID",
    "Index": "Asset_Index",
    "PublicID": "Asset_PublicID",
    "Category": "Amenity_Category",
    "Custom Tags": "Amenity_CustomTags",
    "Caption": "Caption",
    "Description": "Description",
    "Alt Text": "Alt_Text",
    "URL": "Asset_Link",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export curated image content to an Excel file with the ICE content columns."
    )
    parser.add_argument(
        "--input",
        default="output_hotels/all_hotels_cumulative.csv",
        type=Path,
        help="Enriched CSV generated by pipeline.py. Defaults to output_hotels/all_hotels_cumulative.csv.",
    )
    parser.add_argument(
        "--output",
        default="output_hotels/content_export.xlsx",
        type=Path,
        help="Excel file to write. Defaults to output_hotels/content_export.xlsx.",
    )
    parser.add_argument(
        "--delimiter",
        default=";",
        help="Input CSV delimiter. Defaults to ';'.",
    )
    return parser.parse_args()


def source_value(row: Dict[str, str], field: str) -> str:
    return (row.get(field) or "").strip()


def hotel_value(row: Dict[str, str]) -> str:
    return " ".join(
        part
        for part in [
            source_value(row, "Listing_Brand"),
            source_value(row, "Listing_Name"),
        ]
        if part
    )


def build_export_row(row: Dict[str, str]) -> Dict[str, str]:
    export_row = {column: "" for column in EXPORT_COLUMNS}
    for target_column, source_column in SOURCE_COLUMNS.items():
        export_row[target_column] = source_value(row, source_column)
    export_row["Hotel"] = hotel_value(row)
    export_row["AssetType"] = "PH"
    return export_row


def read_export_rows(input_path: Path, delimiter: str = ";") -> List[Dict[str, str]]:
    with input_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle, delimiter=delimiter)
        return [build_export_row(row) for row in reader]


def column_letter(index: int) -> str:
    letters = ""
    while index:
        index, remainder = divmod(index - 1, 26)
        letters = chr(65 + remainder) + letters
    return letters


def cell_xml(reference: str, value: str) -> str:
    text = "" if value is None else str(value)
    space = ' xml:space="preserve"' if text != text.strip() else ""
    return f'<c r="{reference}" t="inlineStr"><is><t{space}>{escape(text)}</t></is></c>'


def worksheet_xml(columns: Sequence[str], rows: Iterable[Dict[str, str]]) -> str:
    row_values = [list(columns)]
    row_values.extend([[row.get(column, "") for column in columns] for row in rows])
    last_cell = f"{column_letter(len(columns))}{len(row_values)}"
    xml_rows = []
    for row_index, values in enumerate(row_values, start=1):
        cells = [
            cell_xml(f"{column_letter(column_index)}{row_index}", value)
            for column_index, value in enumerate(values, start=1)
        ]
        xml_rows.append(f'<row r="{row_index}">{"".join(cells)}</row>')
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        f'<dimension ref="A1:{last_cell}"/>'
        '<sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" '
        'activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>'
        '<sheetData>'
        f'{"".join(xml_rows)}'
        '</sheetData>'
        f'<autoFilter ref="A1:{last_cell}"/>'
        '</worksheet>'
    )


def workbook_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets><sheet name="Content Export" sheetId="1" r:id="rId1"/></sheets>'
        '</workbook>'
    )


def workbook_rels_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
        'Target="worksheets/sheet1.xml"/>'
        '</Relationships>'
    )


def root_rels_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
        'Target="xl/workbook.xml"/>'
        '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" '
        'Target="docProps/core.xml"/>'
        '<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" '
        'Target="docProps/app.xml"/>'
        '</Relationships>'
    )


def content_types_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/docProps/core.xml" '
        'ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>'
        '<Override PartName="/docProps/app.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>'
        '</Types>'
    )


def core_props_xml() -> str:
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/" '
        'xmlns:dcterms="http://purl.org/dc/terms/" '
        'xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
        '<dc:creator>img_content_curation</dc:creator>'
        '<cp:lastModifiedBy>img_content_curation</cp:lastModifiedBy>'
        f'<dcterms:created xsi:type="dcterms:W3CDTF">{timestamp}</dcterms:created>'
        f'<dcterms:modified xsi:type="dcterms:W3CDTF">{timestamp}</dcterms:modified>'
        '</cp:coreProperties>'
    )


def app_props_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" '
        'xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
        '<Application>img_content_curation</Application>'
        '</Properties>'
    )


def write_excel(path: Path, rows: Sequence[Dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("wb", delete=False, dir=path.parent, suffix=".tmp") as handle:
        temp_path = Path(handle.name)
    try:
        with zipfile.ZipFile(temp_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("[Content_Types].xml", content_types_xml())
            archive.writestr("_rels/.rels", root_rels_xml())
            archive.writestr("docProps/core.xml", core_props_xml())
            archive.writestr("docProps/app.xml", app_props_xml())
            archive.writestr("xl/workbook.xml", workbook_xml())
            archive.writestr("xl/_rels/workbook.xml.rels", workbook_rels_xml())
            archive.writestr("xl/worksheets/sheet1.xml", worksheet_xml(EXPORT_COLUMNS, rows))
        temp_path.replace(path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def main() -> int:
    args = parse_args()
    rows = read_export_rows(args.input, delimiter=args.delimiter)
    write_excel(args.output, rows)
    print(f"[DONE] wrote {args.output} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
